{
 "title": "MQTT Dashboard",
 "time": { "from": "now-30s", "to": "now" },
 "templating": {
  "list": [
   { "name": "Equipment", "query": "cell, Rob1, Rob2, Rob3" }
  ]
 },
 "panels": [
  {
   "title": "${Equipment} x-y position",
   "type": "xychart",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "topic": "magna/iotacademy/conestoga/smart/presorter/G2/${Equipment}/ROBOTPOS.X"
    },
    {
     "topic": "magna/iotacademy/conestoga/smart/presorter/G2//${Equipment}/ROBOTPOS.Y"
    }
   ]
  },
  {
   "title": "${Equipment} Motor 1 Torque exceeds 80% of max. / last hour",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH data AS (\r\n  SELECT \r\n    timestamp,\r\n    deviceid,\r\n    metric,\r\n    value,\r\n    \r\n    CASE \r\n      WHEN ABS(value) > 20 THEN 1\r\n      ELSE 0\r\n    END AS above_threshold\r\n  FROM telemetry\r\n  WHERE deviceid = '${Equipment}' \r\n  and metric = 'MACTTORQUE_1'\r\n    AND timestamp >= NOW() - INTERVAL '1 hour'\r\n),\r\n\r\nevents AS (\r\n  SELECT *,\r\n    LAG(above_threshold) OVER (\r\n      PARTITION BY deviceid, metric\r\n      ORDER BY timestamp\r\n    ) AS prev_value\r\n  FROM data\r\n)\r\n\r\nSELECT \r\n  deviceid,\r\n  metric,\r\n  COUNT(*) AS threshold_crossings\r\nFROM events\r\nWHERE above_threshold = 1\r\n  AND COALESCE(prev_value, 0) = 0\r\nGROUP BY deviceid, metric;\r\n"
    }
   ]
  },
  {
   "title": "${Equipment} Motor 2Torque exceeds 80% of max. / last hour",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH data AS (\r\n  SELECT \r\n    timestamp,\r\n    deviceid,\r\n    metric,\r\n    value,\r\n    \r\n    CASE \r\n      WHEN ABS(value) > 20 THEN 1\r\n      ELSE 0\r\n    END AS above_threshold\r\n  FROM telemetry\r\n  WHERE deviceid = '${Equipment}' \r\n  and metric = 'MACTTORQUE_2'\r\n    AND timestamp >= NOW() - INTERVAL '1 hour'\r\n),\r\n\r\nevents AS (\r\n  SELECT *,\r\n    LAG(above_threshold) OVER (\r\n      PARTITION BY deviceid, metric\r\n      ORDER BY timestamp\r\n    ) AS prev_value\r\n  FROM data\r\n)\r\n\r\nSELECT \r\n  deviceid,\r\n  metric,\r\n  COUNT(*) AS threshold_crossings\r\nFROM events\r\nWHERE above_threshold = 1\r\n  AND COALESCE(prev_value, 0) = 0\r\nGROUP BY deviceid, metric;\r\n"
    }
   ]
  },
  {
   "title": "${Equipment} Motor 3 Torque exceeds 80% of max. / last hour",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 10, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH data AS (\r\n  SELECT \r\n    timestamp,\r\n    deviceid,\r\n    metric,\r\n    value,\r\n    \r\n    CASE \r\n      WHEN ABS(value) > 20 THEN 1\r\n      ELSE 0\r\n    END AS above_threshold\r\n  FROM telemetry\r\n  WHERE deviceid = 'Rob1' \r\n  and metric = 'MACTTORQUE_3'\r\n    AND timestamp >= NOW() - INTERVAL '1 hour'\r\n),\r\n\r\nevents AS (\r\n  SELECT *,\r\n    LAG(above_threshold) OVER (\r\n      PARTITION BY deviceid, metric\r\n      ORDER BY timestamp\r\n    ) AS prev_value\r\n  FROM data\r\n)\r\n\r\nSELECT \r\n  deviceid,\r\n  metric,\r\n  COUNT(*) AS threshold_crossings\r\nFROM events\r\nWHERE above_threshold = 1\r\n  AND COALESCE(prev_value, 0) = 0\r\nGROUP BY deviceid, metric;\r\n"
    }
   ]
  },
  {
   "title": "${Equipment} Motor 4 Torque exceeds 80% of max. / last hour",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH data AS (\r\n  SELECT \r\n    timestamp,\r\n    deviceid,\r\n    metric,\r\n    value,\r\n    \r\n    CASE \r\n      WHEN ABS(value) > 20 THEN 1\r\n      ELSE 0\r\n    END AS above_threshold\r\n  FROM telemetry\r\n  WHERE deviceid = 'Rob1' \r\n  and metric = 'MACTTORQUE_4'\r\n    AND timestamp >= NOW() - INTERVAL '1 hour'\r\n),\r\n\r\nevents AS (\r\n  SELECT *,\r\n    LAG(above_threshold) OVER (\r\n      PARTITION BY deviceid, metric\r\n      ORDER BY timestamp\r\n    ) AS prev_value\r\n  FROM data\r\n)\r\n\r\nSELECT \r\n  deviceid,\r\n  metric,\r\n  COUNT(*) AS threshold_crossings\r\nFROM events\r\nWHERE above_threshold = 1\r\n  AND COALESCE(prev_value, 0) = 0\r\nGROUP BY deviceid, metric;\r\n"
    }
   ]
  },
  {
   "title": "${Equipment} initialized",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  CASE \r\n    WHEN status = true THEN 1\r\n    ELSE 0\r\n  END as status_value\r\nFROM equipment_status\r\nWHERE deviceid = '${Equipment}'\r\nAND status_name = 'INITIALIZED'\r\nORDER BY timestamp DESC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "${Equipment} Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  CASE \r\n    WHEN status = true THEN 1\r\n    ELSE 0\r\n  END as status_value\r\nFROM equipment_status \r\nWHERE deviceid = '${Equipment}'\r\nAND status_name = 'RUNNING'\r\nORDER BY timestamp DESC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "${Equipment} Paused",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  CASE \r\n    WHEN status = true THEN 1\r\n    ELSE 0\r\n  END as status_value\r\nFROM equipment_status\r\nWHERE deviceid = '${Equipment}'\r\nAND status_name = 'PAUSED'\r\nORDER BY timestamp DESC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "${Equipment} Violation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  CASE \r\n    WHEN status = true THEN 1\r\n    ELSE 0\r\n  END as status_value\r\nFROM equipment_status\r\nWHERE deviceid = '${Equipment}'\r\nAND status_name = 'WSVIOLATION'\r\nORDER BY timestamp DESC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "${Equipment} Torque",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "forceNm" } },
   "targets": [
    {
     "topic": "magna/iotacademy/conestoga/smart/presorter/G2//${Equipment}/MACTTORQUE_1"
    },
    {
     "topic": "magna/iotacademy/conestoga/smart/presorter/G2//${Equipment}/MACTTORQUE_2"
    },
    {
     "topic": "magna/iotacademy/conestoga/smart/presorter/G2//${Equipment}/MACTTORQUE_3"
    },
    {
     "topic": "magna/iotacademy/conestoga/smart/presorter/G2//${Equipment}/MACTTORQUE_4"
    }
   ]
  }
 ]
}